## **HW#0-STA208-S24: Getting Started / Warmup Exercises**

## Part I: (Do not turn in)

Basics of how to work with jupyter notebooks and colab.

**Colab/notebooks:**

- colab and google drive
- code cells / text cells
- save (and pin) notebooks
- markdown
- latex

- I/O (see below; reference: https://colab.research.google.com/notebooks/io.ipynb)

**Resources:**

[Very basics of LATEX](https://en.wikibooks.org/wiki/LaTeX/Mathematics)

[Overview of Colaboratory](https://colab.research.google.com/notebooks/basic_features_overview.ipynb)

[Guide to Markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb)

[Saving and loading notebooks in GitHub](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)



### I/O on Colab and using bash commands (this section is also in the notebook "lecture1")

To upload a file to Colab from a local drive, run the following code (you will be prompted to select the file);

In [1]:
from google.colab import files
uploaded = files.upload()

# the below shows that I have imported the file "winequality-red.csv" (to do this click 
# on the prompt "Choose Files" and select from your loval machine)

ModuleNotFoundError: No module named 'google'

- Alternatively, you can also mount your entire google drive, and then have access to all the files there; after mounting google drive there is no need to individually upload files; 
- To mount google drive, you can either click on the corresponding "mount" icon in the left column under 'Files', or run the next code cell, or use below code;
- then run the subsequent code cell to load the `winequality' data


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
## Lines that start with ! run a bash (shell) command

# If mounting google drive, run the following to see whether the winedata file is accessible
# !ls -l /content/drive/MyDrive/data/winequality-red.csv

# if uploading the data from a local drive, run the following to see whether the winedata file is accessible
!ls -l winequality-red.csv

-rw-r--r-- 1 root root 84199 Apr  1 16:26 winequality-red.csv


In [ ]:
# If google drive has been mounted, run the following to see the header of the file
# !head /content/drive/MyDrive/data/winequality-red.csv

# If data file has been loaded from a local drive, run the following to see the header of the file
!head winequality-red.csv

"fixed acidity";"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5
7.8;0.88;0;2.6;0.098;25;67;0.9968;3.2;0.68;9.8;5
7.8;0.76;0.04;2.3;0.092;15;54;0.997;3.26;0.65;9.8;5
11.2;0.28;0.56;1.9;0.075;17;60;0.998;3.16;0.58;9.8;6
7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5
7.4;0.66;0;1.8;0.075;13;40;0.9978;3.51;0.56;9.4;5
7.9;0.6;0.06;1.6;0.069;15;59;0.9964;3.3;0.46;9.4;5
7.3;0.65;0;1.2;0.065;15;21;0.9946;3.39;0.47;10;7
7.8;0.58;0.02;2;0.073;9;18;0.9968;3.36;0.57;9.5;7



### Review basics of python, numpy, pandas
(official Python documentation: https://docs.python.org/3/)

- lists, tuples, arrays (perhaps dictionaries, sets)
- functions
- if else; for loops
- [f(a) for a in L] list comprehension (e.g. see https://www.pythoncheatsheet.org/cheatsheet/comprehensions)
- copying vs. referencing
- mutable - immutable (e.g. see https://realpython.com/python-mutable-vs-immutable-types/)

<br>

- slicing a numpy array
- pandas dataframes (e.g. see https://pandas.pydata.org/docs/reference/frame.html)
- slicing a pandas dataframe
- subsetting using iloc and loc
- subsetting using criteria
- fit(), predict(), transform() (fit_predict(), fit_transfrom()) methods

**General resources:**
- https://www.pythoncheatsheet.org/
- https://pandas.pydata.org/docs/reference/io.html



### Part II: Some Exercises (turn in for credit)

These exercises are meant to recall basic geometric interpretation underlying concepts from linear algebra and to get some practice in using basic numpy/python.


1) Add a new text cell to this notebook right below the fomulation of this problem 1 (in particular, split the cell - see keyboard shortcuts in the tools dropdown menu for the command) and add your answers to this problem there. Use LATEX for writing formulas.

Suppose $u$ is a $d$-dimensional vector that is normal to a hyperplane $H$. Consider the $(d \times d)$-matrix

$$U := I_d - \frac{1}{\|u\|^2}uu^\top.$$

a) Show that for any $d$-dimensional vector $v$, the vector $Uv$ (matrix multiplication) lies in $H$. [HINT: Show this by using the property of a normal vector.]

b) Provide a geometric interpretation of the vector $Uv$ (i.e. describe how it relates geometrically to $v$).

c) With $I_d$ denoting the $(d \times d)$_identity matrix, the matrix

$$U^* := I_d - \frac{2}{\|u\|^2}uu^\top$$

is called *elementary reflector* (or sometimes *Hausholder transformation*). Compare the vector $U^*v$ to $Uv$ and explain the name *elementary reflector*. [HINT: Drawing a figure for $d=2$ might help.]


ANS: a) Given the matrix $U$ defined as $U = I_d - \frac{1}{\|u\|^2}uu^\top$, and the vector $v$, the operation $Uv$ is given by:

$$
Uv = v - \frac{1}{\|u\|^2}uu^\top v
$$

Multiplying both sides by $u^\top$ from the left:

$$
u^\top (Uv) = u^\top \left( v - \frac{1}{\|u\|^2}uu^\top v \right)
$$

Expanding the right-hand side:

$$
u^\top (Uv) = u^\top v - u^\top \left( \frac{1}{\|u\|^2}uu^\top v \right)
$$

Since $u^\top u = \|u\|^2$, this simplifies to:

$$
u^\top (Uv) = u^\top v - \frac{\|u\|^2}{\|u\|^2}u^\top v = u^\top v - u^\top v = 0
$$

Therefore, $u^\top (Uv) = 0$, which implies $Uv$ is orthogonal to $u$ and hence lies in the hyperplane $H$.


ANS: b) The matrix $U$ projects $v$ onto the hyperplane $H$. The vector $Uv$ can be seen as the component of $v$ that lies entirely in the hyperplane $H$ orthogonal to $u$.




ANS: c) Given the matrix $U^*$ defined as $U^* = I_d - \frac{2}{\|u\|^2}uu^\top$, and the vector $v$, given the formula above that $Uv = v - \frac{1}{\|u\|^2}uu^\top v$, the operation $U^*v$ is given by:

$$
U^*v = v - \frac{2}{\|u\|^2}uu^\top v = Uv-\frac{1}{\|u\|^2}uu^\top v
$$

As we proved before, Uv lies on hyperplane $H$, which is the component of $v$ that lies entirely in the hyperplane $H$ orthogonal to $u$. On the other hand, $\frac{1}{\|u\|^2}uu^\top v$ calculates the projection of $v$ onto the direction of $u$. This projection is the component of $v$ that is parallel to $u$. $Uv-\frac{1}{\|u\|^2}uu^\top v$, i.e. by subtracting the projection $Uv$ from $v$, the result is a vector that has been "reflected" across the hyperplane. The subtraction effectively removes the component of $v$ that is parallel to $u$ and replaces it with its inverse, while the component of $v$ that lies in the hyperplane $H$ remains unchanged. That's why it called element reflector.


2) Use numpy to do the computations in this problem. To this end, use this notebook, add a code cell right below the formulation of this problem and put your solutions there.

a) Define $u = (1,2,3,3,2,1)$, $v = (1,2,3,4,5,6).$
- Compute the matrix $U = I - \frac{1}{\|u\|^2}uu^\top$ and find $Uv$ (print both, the matrix $U$ and the vector $Uv$)
- Compute $U^* = I - \frac{2}{\|u\|^2}uu^\top$ and find $U^*v$ (print both, the matrix $U^*$ and the vector $U^*v$).

b)  Consider the real value
$\alpha = \frac{\langle u, Uv-U^*v\rangle}{\|u\|\cdot\|Uv - U^*v\|}.$
- Make a conjecture of what the value of $\alpha$ is (use your geometric intuition - again, drawing a figure in $d=2$ should help).
- Compute $\alpha$, and explain the value you obtain.


In [3]:
# a)
import numpy as np
# 1)
u = np.array([1, 2, 3, 3, 2, 1])
v = np.array([1, 2, 3, 4, 5, 6])
I = np.eye(len(u))
norm_u_squared = np.dot(u,u)
U = I - (np.outer(u, u) / norm_u_squared)
Uv = np.dot(U, v)
print(U)
print(Uv)
# 2)
U_star = I - 2*(np.outer(u, u) / norm_u_squared)
U_star_v = np.dot(U_star, v)
print(U_star)
print(U_star_v)

[[ 0.96428571 -0.07142857 -0.10714286 -0.10714286 -0.07142857 -0.03571429]
 [-0.07142857  0.85714286 -0.21428571 -0.21428571 -0.14285714 -0.07142857]
 [-0.10714286 -0.21428571  0.67857143 -0.32142857 -0.21428571 -0.10714286]
 [-0.10714286 -0.21428571 -0.32142857  0.67857143 -0.21428571 -0.10714286]
 [-0.07142857 -0.14285714 -0.21428571 -0.21428571  0.85714286 -0.07142857]
 [-0.03571429 -0.07142857 -0.10714286 -0.10714286 -0.07142857  0.96428571]]
[-0.5 -1.  -1.5 -0.5  2.   4.5]
[[ 0.92857143 -0.14285714 -0.21428571 -0.21428571 -0.14285714 -0.07142857]
 [-0.14285714  0.71428571 -0.42857143 -0.42857143 -0.28571429 -0.14285714]
 [-0.21428571 -0.42857143  0.35714286 -0.64285714 -0.42857143 -0.21428571]
 [-0.21428571 -0.42857143 -0.64285714  0.35714286 -0.42857143 -0.21428571]
 [-0.14285714 -0.28571429 -0.42857143 -0.42857143  0.71428571 -0.14285714]
 [-0.07142857 -0.14285714 -0.21428571 -0.21428571 -0.14285714  0.92857143]]
[-2. -4. -6. -5. -1.  3.]


ANS: b) Let's decompose the formula:
$$
Uv - U^*v = Uv - (v - \frac{2}{\|u\|^2}uu^\top v) = Uv - (Uv-\frac{1}{\|u\|^2}uu^\top v) = \frac{1}{\|u\|^2}uu^\top v
$$
which is the projection of $v$ on $u$, which could has the same direction of $u$ or opposite the direction of $u$.

Thus, the numerator $<u,\frac{1}{\|u\|^2}uu^\top v>$ is the product of the norm of $u$ and the norm of the difference between $Uv$ and  $U^*v$, which is the scaled squared norm of u, with the sign positive or negative.
Since the denominator is also the the difference between $Uv$ and  $U^*v$, so $\alpha$ will be either 1 or -1, depending on the orientation of $u$ with respect to $Uv - U^*v$.


In [4]:
dot_product = np.dot(u, Uv - U_star_v)
norm_u = np.linalg.norm(u)
norm_difference = np.linalg.norm(Uv - U_star_v)
alpha = dot_product / (norm_u * norm_difference)
print(alpha)

0.9999999999999998


ANS: In this computation, the alpha is 1, which means the orientation of $u$ align with respect to $Uv - U^*v$, the v is lie on the opposite sides of the hyperplane $H$ compared to u.

3) Consider the matrix $UU^\top$ with $U$ from above. We are now concerned about the eigenvalues of $UU^\top$.

- Make a conjecture about the values of the eigenvalues of $UU^\top$ (positive, negative, zero, certain specific values??).

- Compute the eigenvalues using numpy and iterprete the values that you find.

- Explain why $UU^\top = UU = U$, i.e. $U$ is idempotent.

- Let $V$ be the $(6 \times 3)$-matrix consisting of the first three columns of $U$. Is $V$ also idempotent? Explain.

3.1 ANS: Given that $U$ projects vectors onto a hyperplane orthogonal to $u$, reducing components along $u$ to zero while preserving components orthogonal to $u$, the expected eigenvalues of $UU^\top$ are:
- **1** for dimensions unaffected by $U$, indicating directions orthogonal to $u$.
- **0** for the dimension aligned with $u$, where the projection nullifies components.

Negative or complex eigenvalues are unlikely for $U$ as it does not entail operations (like rotation or reflection) that could produce such eigenvalues, being a straightforward projection matrix.

In [6]:
# 2)
UU_T = np.dot(U, U.T)
eigenvalues_UU_T, _ = np.linalg.eig(UU_T)
print(eigenvalues_UU_T)

[ 1.00000000e+00 -2.14027754e-17  1.00000000e+00  1.00000000e+00
  1.00000000e+00  1.00000000e+00]


In [8]:
UU_T.T

array([[ 0.96428571, -0.07142857, -0.10714286, -0.10714286, -0.07142857,
        -0.03571429],
       [-0.07142857,  0.85714286, -0.21428571, -0.21428571, -0.14285714,
        -0.07142857],
       [-0.10714286, -0.21428571,  0.67857143, -0.32142857, -0.21428571,
        -0.10714286],
       [-0.10714286, -0.21428571, -0.32142857,  0.67857143, -0.21428571,
        -0.10714286],
       [-0.07142857, -0.14285714, -0.21428571, -0.21428571,  0.85714286,
        -0.07142857],
       [-0.03571429, -0.07142857, -0.10714286, -0.10714286, -0.07142857,
         0.96428571]])

3.2 ANS: The eigenvalues of $UU^\top$ are \(1, 0, 1, 1, 1, 1\), with the multiple 1s indicating directions orthogonal to $u$ that remain unaffected by the projection, preserving their magnitude. The eigenvalue approximately 0 signifies the dimension along $u$ being reduced to zero by the projection, reflecting the reduction in dimensionality as vectors align with the hyperplane.


3.3 ANS: The matrix $U = I_d - \frac{1}{\|u\|^2}uu^\top$ is an idempotent matrix that $UU = U$. This is a characteristic feature of projection matrices. This idempotency stems from $U$'s function to project vectors onto a hyperplane orthogonal to $u$. The essence of projection ensures that once a vector is projected (flattened against the hyperplane), subsequent projections by $U$ maintain the vector unchanged. 

In [11]:
V = U[:, :3]

# Compute V*V^T and V^T*V to analyze if V is idempotent
VV_T = np.dot(V, V.T)
V_T_V = np.dot(V.T, V)

print(V)
print(VV_T)
print(V_T_V)

[[ 0.96428571 -0.07142857 -0.10714286]
 [-0.07142857  0.85714286 -0.21428571]
 [-0.10714286 -0.21428571  0.67857143]
 [-0.10714286 -0.21428571 -0.32142857]
 [-0.07142857 -0.14285714 -0.21428571]
 [-0.03571429 -0.07142857 -0.10714286]]
[[ 0.94642857 -0.10714286 -0.16071429 -0.05357143 -0.03571429 -0.01785714]
 [-0.10714286  0.78571429 -0.32142857 -0.10714286 -0.07142857 -0.03571429]
 [-0.16071429 -0.32142857  0.51785714 -0.16071429 -0.10714286 -0.05357143]
 [-0.05357143 -0.10714286 -0.16071429  0.16071429  0.10714286  0.05357143]
 [-0.03571429 -0.07142857 -0.10714286  0.10714286  0.07142857  0.03571429]
 [-0.01785714 -0.03571429 -0.05357143  0.05357143  0.03571429  0.01785714]]
[[ 0.96428571 -0.07142857 -0.10714286]
 [-0.07142857  0.85714286 -0.21428571]
 [-0.10714286 -0.21428571  0.67857143]]


3.4 ANS: Examining the idempotency of a non-square matrix $V$, composed of the first three columns of $U$, through $VV^\top$ and $V^\top V$, reveals that idempotency, typically defined as $A^2 = A$ for square matrices, is not applicable to $V$. Specifically:
- $VV^\top$ yields a $6 \times 6$ matrix, suggesting transformations within a $6$-dimensional space, but does not equate to $V$ or an identity matrix, indicating the absence of idempotent characteristics in $V$.
- Conversely, $V^\top V$ produces a $3 \times 3$ matrix, which, despite aligning more closely with $V$'s structural essence, fails to fulfill the idempotency criterion by not replicating $V$ or an identity matrix.

Therefore, $V$ does not qualify as idempotent. This analysis underscores $V$'s role in facilitating transformations across its subspaces, diverging from the square matrix requirement for idempotency.

4) Some numpy practice: With $U = (U_{ij})_{i,j=1,\ldots,6}$ from above do the following:

- Find the largest and smallest off-diagonal elements of $UU^\top$.

- Find the largest and smallest diagonal elements of $UU^\top$.

- Compute the value $max_i \sum_{j} |U_{ij}|$.

- Print the elements of the second column of $UU^\top$ below the diagonal.

- Verify idempotence of $U$ by showing that $UU - U = 0$ (where the $0$ on the right hand side is the $0$-matrix).




In [39]:
# 4
# 1) Find the largest and smallest off-diagonal elements of UU^T
off_diagonal_elements = UU_T[~np.eye(UU_T.shape[0], dtype=bool)] # Extracting off-diagonal elements
largest_off_diagonal = np.max(off_diagonal_elements)
smallest_off_diagonal = np.min(off_diagonal_elements)
print(largest_off_diagonal)
print(smallest_off_diagonal)

# 2) Find the largest and smallest diagonal elements of UU^T
diagonal_elements = np.diag(UU_T)
largest_diagonal = np.max(diagonal_elements)
smallest_diagonal = np.min(diagonal_elements)
print(largest_diagonal)
print(smallest_diagonal)

# 3) Compute the value max_i sum_{j} |U_{ij}|
max_sum_abs_U_ij = np.max(np.sum(np.abs(U), axis=1))
print(max_sum_abs_U_ij)

# 4) Print the elements of the second column of UU^T below the diagonal
second_column_below_diagonal = UU_T[2:, 1]
print(second_column_below_diagonal)

# 5) # Verify idempotence of U by showing that UU - U = 0
idempotence = np.dot(U, U.T) - U
print(np.allclose(idempotence, 0))

-0.03571428571428571
-0.3214285714285715
0.9642857142857143
0.6785714285714286
1.6428571428571428
[-0.21428571 -0.21428571 -0.14285714 -0.07142857]
True
